api_platform:
    title: Hello API Platform
    version: 1.0.0
    # Mercure integration, remove if unwanted
    mercure:
        include_type: true
    # Good defaults for REST APIs
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
        route_prefix: api
    path_segment_name_generator: api_platform.metadata.path_segment_name_generator.dash
    mapping:
        paths: ['%kernel.project_dir%/src/Entity', '%kernel.project_dir%/src/ApiResource']
